config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

    has_many :comments ,dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @post=Post.find(params[:post_id])
        @post.comments.create(comment_params)
        redirect_to post_path(@post)
        
    end

    def destroy
        @post=Post.find(params[:post_id])
        @comment=@post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private
    
        def comment_params
            params.require(:comment).permit(:name,:comment)
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def index
        @posts=Post.all.order("created_at DESC")
    end

    def new
        @post=Post.new
    end

    def create
        @post=Post.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end


    def show
        @post=Post.find(params[:id])
    end

    def edit
        @post=Post.find(params[:id])
    end

    def update
        @post=Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else
            render "edit"
        end
    end

    def destroy
        @post=Post.find(params[:id])
        @post.destroy
        redirect_to root_path
    end
    private

    def post_params
        params.require(:post).permit(:title,:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
<div class="media">
    <div class="media-content">
        <span class="title is-4"> <%= comment.name %></span>
        <div class="content">
            <p>
                <%= comment.comment %>
            </p>
        
        </div>
    </div>

    <%= link_to 'Delete', post_comment_path(comment.post,comment) ,class:"button is-danger",method: :delete,data:{confirm:"Are you sure ?"}%>

</div>

</div>

app/views/comments/_form.html.erb
<%=simple_form_for([@post,@post.comments.build]) do |f| %>

<div class="field">
    <div class="control">
        <%= f.input :name,input_html:{class:"input"},wrapper: false,label_html:{class:"label"} %>
    </div>
</div>


<div class="field">
    <div class="control">
        <%= f.input :comment,input_html:{class:"textarea"},wrapper: false,label_html:{class:"label"} %>
    </div>
</div>

<%= f.button  :submit,class:"button is-primary"%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar is-info" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
    <a href="#" class="navbar-item title">Blog</a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>
      <%= link_to 'new post', new_post_path ,class:"navbar-item" %>    
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
  </div>
  
</nav>
<div container>

  <%= yield %>
</div>
    
  </body>
</html>

app/views/posts/_form.html.erb
<%=simple_form_for(@post) do |f| %>

<div class="field">
    <div class="control">
        <%= f.input :title,input_html:{class:"input"},wrapper: false,label_html:{class:"label"} %>
    </div>
</div>


<div class="field">
    <div class="control">
        <%= f.input :content,input_html:{class:"textarea"},wrapper: false,label_html:{class:"label"} %>
    </div>
</div>

<%= f.button  :submit,class:"button is-primary"%>

<% end %>

app/views/posts/edit.html.erb
<h2 class="title">Edit Post</h2>

<div class="section">
<div class="container">
    <%= render "form" %>
</div>
</div>

app/views/posts/index.html.erb
<section class="section">
    <div class="container">
    <h2 class="title">Blog index</h2>

    <% if @posts.blank? %>
        <article class="message is-warning">
        <div class="message-header">
            <p>Warning</p>
            <button class="delete" aria-label="delete"></button>
        </div>
        <div class="message-body">
            Sorry there are any posts unitil right now
        </div>
        </article>      
    <% end %>
    <% @posts.each do |post| %>
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <h3 class="title is-4"><%= link_to post.title,post_path(post) %></h3>
                    </div>
                </div>
            </div>

            <div class="content">
                <%= post.content %>
            </div>
        </div>

    <% end %>
    
    </div>

</section>

app/views/posts/new.html.erb
<div class="section">

<div class="container">
<h2 class="title">New Post</h2>
    <%= render "form" %>
</div>

</div>

app/views/posts/show.html.erb
<div class="section">
    <div class="container">
        <h2 class="title">Show Post</h2>
        <div class="navbar-menu">
        <div class="navbar-start">
            <a href="#" class="navabar-item">Actions</a>
        </div>

        <div class="navbar-end">
            <!-- navbar items -->
            <p class="control navbar-item">
                <%= link_to 'Edit', edit_post_path(@post) ,class:"button is-warning" %>
            </p>

            <p class="control navbar-item">
                
                 <%= link_to 'Delete', post_path(@post) ,class:"button is-danger",method: :delete,data:{confirm:"Are you sure ?"} %>
            </p>
        </div>
        </div>
        <hr/>
        <h3 class="title"><%= @post.title %></h3>
        <div class="content"><%= @post.content %></div>



       <section class="section comments">
        <div class="container">
            <h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
            <%= render @post.comments %>
            <div class="comment-form">
                <hr />
                <h3 class="subtitle is-3">Leave a reply</h3>
                <%= render 'comments/form' %>
            </div>
        </div>
       </section>
    
    </div>
</div>